import Enums from '../../misc/Enums.js?v=fix_3';
import Brush from './Brush.js?v=fix_3';
import Inflate from './Inflate.js?v=fix_3';
import Twist from './Twist.js?v=fix_3';
import Smooth from './Smooth.js?v=fix_3';
import Flatten from './Flatten.js?v=fix_3';
import Pinch from './Pinch.js?v=fix_3';
import Crease from './Crease.js?v=fix_3';
import Drag from './Drag.js?v=fix_3';
import Paint from './Paint.js?v=fix_3';
import Move from './Move.js?v=fix_3';
import Masking from './Masking.js?v=fix_3';
import LocalScale from './LocalScale.js?v=fix_3';
import Transform from './Transform.js?v=fix_3';
import SculptVoxel from './SculptVoxel.js?v=fix_3';
import Grab from './Grab.js?v=fix_3';

var Tools = [];

Tools[Enums.Tools.BRUSH] = Brush;
Tools[Enums.Tools.INFLATE] = Inflate;
Tools[Enums.Tools.TWIST] = Twist;
Tools[Enums.Tools.SMOOTH] = Smooth;
Tools[Enums.Tools.FLATTEN] = Flatten;
Tools[Enums.Tools.PINCH] = Pinch;
Tools[Enums.Tools.CREASE] = Crease;
Tools[Enums.Tools.DRAG] = Drag;
Tools[Enums.Tools.PAINT] = Paint;
Tools[Enums.Tools.MOVE] = Move;
Tools[Enums.Tools.MASKING] = Masking;
Tools[Enums.Tools.LOCALSCALE] = LocalScale;
Tools[Enums.Tools.TRANSFORM] = Transform;
Tools[Enums.Tools.VOXEL] = SculptVoxel;
Tools[Enums.Tools.GRAB] = Grab;

Tools[Enums.Tools.BRUSH].uiName = 'sculptBrush';
Tools[Enums.Tools.INFLATE].uiName = 'sculptInflate';
Tools[Enums.Tools.TWIST].uiName = 'sculptTwist';
Tools[Enums.Tools.SMOOTH].uiName = 'sculptSmooth';
Tools[Enums.Tools.FLATTEN].uiName = 'sculptFlatten';
Tools[Enums.Tools.PINCH].uiName = 'sculptPinch';
Tools[Enums.Tools.CREASE].uiName = 'sculptCrease';
Tools[Enums.Tools.DRAG].uiName = 'sculptDrag';
Tools[Enums.Tools.PAINT].uiName = 'sculptPaint';
Tools[Enums.Tools.MOVE].uiName = 'sculptMove';
Tools[Enums.Tools.MASKING].uiName = 'sculptMasking';
Tools[Enums.Tools.LOCALSCALE].uiName = 'sculptLocalScale';
Tools[Enums.Tools.TRANSFORM].uiName = 'sculptTransform';
Tools[Enums.Tools.VOXEL].uiName = 'sculptVoxel';
Tools[Enums.Tools.GRAB].uiName = 'sculptGrab';

export default Tools;
