// Catmull-Clark stencils from NOMAD'S OWN face lists. Imports nothing, so it runs under node.
//
// WHY THIS EXISTS. SculptXR subdivides with SculptGL's rules: Catmull-Clark for quads but LOOP for
// triangles (one triangle -> four triangles, no face point). Nomad is Catmull-Clark everywhere (one
// triangle -> three quads, with a face point). A Nomad cage with even a handful of triangles (a
// pole, a seam) therefore subdivides to a DIFFERENT vertex count here, and the two can never agree.
// So the levels are not generated by SculptXR's subdivision at all: a level's faces come from the
// file, and the positions that subdivision would give are produced by a stencil built here.
//
// A stencil is the whole subdivision as a sparse linear map: new_vertex[j] = sum w * old_vertex[i].
// Catmull-Clark is linear in the positions, so it also serves colours and materials, and applying it
// is a flat loop (cheap enough for the skin pass, which synthesises every level every frame).
//
// STRUCTURE IS READ FROM THE FILE, NOT ASSUMED: each parent face is followed (in the child list) by
// one child per corner, each child carrying one OLD vertex, the shared FACE point and two EDGE points.
// Edge points are identified by being shared between the children of neighbouring corners.
//
// RULES (checked against the offsets stored in real files, see scratchpad/nomstencil_test.mjs):
//   face point    average of the face's corners
//   edge point    interior: (a + b + Fp + Fq) / 4        boundary / non-manifold: (a + b) / 2
//   old vertex    interior: (F + 2R + (n-3)P) / n        boundary: (prev + 6P + next) / 8
//                 with F the mean of the incident face points and R the mean of the incident
//                 edge midpoints

const TRI = 4294967295;
const sizeOf = (a, o) => (a[o + 3] < 0 || a[o + 3] === TRI ? 3 : 4);

// parent/kids: face arrays with 4 entries per face (the 4th is -1 or TRI_INDEX for a triangle).
// nOld/nNew: vertex counts. Returns { n, start, idx, w } (CSR over the NEW vertices) or null if the
// kid list does not have the structure described above.
export function buildStencil(parent, kids, nOld, nNew) {
  const nP = (parent.length / 4) | 0;
  const pStart = new Int32Array(nP + 1);
  for (let p = 0; p < nP; p++) pStart[p + 1] = pStart[p] + sizeOf(parent, p * 4);
  if (pStart[nP] * 4 !== kids.length) return null;           // one child per parent corner

  const faceVert = new Int32Array(nP);                         // parent -> its face-point id
  const edgeVert = new Int32Array(pStart[nP]);                 // parent corner i -> edge point on (c_i, c_i+1)
  for (let p = 0; p < nP; p++) {
    const n = sizeOf(parent, p * 4), base = pStart[p];
    const child = new Array(n);                                // corner i -> its child's 4 ids, old vertex first
    const taken = new Uint8Array(n);
    for (let j = 0; j < n; j++) {
      const q = [kids[(base + j) * 4], kids[(base + j) * 4 + 1], kids[(base + j) * 4 + 2], kids[(base + j) * 4 + 3]];
      const at = q.findIndex((x) => x >= 0 && x < nOld);
      if (at < 0) return null;
      const rot = [q[at], q[(at + 1) % 4], q[(at + 2) % 4], q[(at + 3) % 4]];
      let i = -1;
      for (let c = 0; c < n; c++) if (parent[p * 4 + c] === rot[0] && !taken[c]) { i = c; break; }
      if (i < 0) return null;
      taken[i] = 1; child[i] = rot;
    }
    const F = child[0][2];
    faceVert[p] = F;
    for (let i = 0; i < n; i++) {
      if (child[i][2] !== F) return null;
      const nxt = child[(i + 1) % n];
      // the edge point on (c_i, c_i+1) is the one id both children carry besides F
      const common = [];
      for (const x of child[i]) if (x !== F && x >= nOld && nxt.includes(x)) common.push(x);
      if (common.length !== 1) return null;
      edgeVert[base + i] = common[0];
    }
  }

  // edges: key -> { id, faces[] }; vertex -> incident faces and edge neighbours
  const edges = new Map();
  const vFaces = Array.from({ length: nOld }, () => []);
  const vNbr = Array.from({ length: nOld }, () => []);
  for (let p = 0; p < nP; p++) {
    const n = sizeOf(parent, p * 4), base = pStart[p];
    for (let i = 0; i < n; i++) {
      const a = parent[p * 4 + i], b = parent[p * 4 + (i + 1) % n];
      vFaces[a].push(p);
      const key = a < b ? a * nOld + b : b * nOld + a;
      let e = edges.get(key);
      if (!e) { e = { a, b, id: edgeVert[base + i], faces: [] }; edges.set(key, e); vNbr[a].push(e); vNbr[b].push(e); }
      e.faces.push(p);
    }
  }

  const rows = new Array(nNew);
  const addTo = (m, i, w) => m.set(i, (m.get(i) || 0) + w);
  const faceRow = (p, scale, m) => {
    const n = sizeOf(parent, p * 4);
    for (let i = 0; i < n; i++) addTo(m, parent[p * 4 + i], scale / n);
  };

  for (let p = 0; p < nP; p++) {
    const m = new Map(); faceRow(p, 1, m); rows[faceVert[p]] = m;
  }
  for (const e of edges.values()) {
    const m = new Map();
    if (e.faces.length === 2) {
      addTo(m, e.a, 0.25); addTo(m, e.b, 0.25);
      faceRow(e.faces[0], 0.25, m); faceRow(e.faces[1], 0.25, m);
    } else { addTo(m, e.a, 0.5); addTo(m, e.b, 0.5); }
    rows[e.id] = m;
  }
  for (let v = 0; v < nOld; v++) {
    const m = new Map(), faces = vFaces[v], nbr = vNbr[v];
    const boundary = nbr.filter((e) => e.faces.length === 1);
    const nonManifold = nbr.some((e) => e.faces.length > 2);
    if (!faces.length) addTo(m, v, 1);
    else if (nonManifold || (boundary.length && boundary.length !== 2)) addTo(m, v, 1);
    else if (boundary.length === 2) {
      addTo(m, v, 0.75);
      for (const e of boundary) addTo(m, e.a === v ? e.b : e.a, 0.125);
    } else {
      const n = faces.length;                                  // interior: valence = incident faces
      addTo(m, v, (n - 3) / n);
      for (const f of faces) faceRow(f, 1 / (n * n), m);       // F: mean of n face points, times 1/n
      for (const e of nbr) { addTo(m, v, 1 / (n * n)); addTo(m, e.a === v ? e.b : e.a, 1 / (n * n)); }   // 2R / n
    }
    rows[v] = m;
  }
  for (let j = 0; j < nNew; j++) if (!rows[j]) return null;

  let total = 0; for (const m of rows) total += m.size;
  const start = new Uint32Array(nNew + 1), idx = new Int32Array(total), w = new Float32Array(total);
  let k = 0;
  for (let j = 0; j < nNew; j++) {
    start[j] = k;
    for (const [i, wt] of rows[j]) { idx[k] = i; w[k++] = wt; }
  }
  start[nNew] = k;
  return { n: nNew, nOld, start, idx, w };
}

// out[j] = sum w * src[i] for the first `count` new vertices; src/out are vec3 arrays
export function applyStencil(st, src, out, count) {
  const n = Math.min(count === undefined ? st.n : count, st.n);
  const { start, idx, w } = st;
  for (let j = 0; j < n; j++) {
    let x = 0, y = 0, z = 0;
    for (let k = start[j], e = start[j + 1]; k < e; k++) {
      const s = idx[k] * 3, wt = w[k];
      x += wt * src[s]; y += wt * src[s + 1]; z += wt * src[s + 2];
    }
    out[j * 3] = x; out[j * 3 + 1] = y; out[j * 3 + 2] = z;
  }
}
