import Enums from '../../misc/Enums.js';
import Brush from './Brush.js';
import Inflate from './Inflate.js';
import Twist from './Twist.js';
import Smooth from './Smooth.js';
import Flatten from './Flatten.js';
import Pinch from './Pinch.js';
import Crease from './Crease.js';
import Drag from './Drag.js';
import Slide from './Slide.js';
import Relax from './Relax.js';
import Paint from './Paint.js';
import Move from './Move.js';
import Masking from './Masking.js';
import LocalScale from './LocalScale.js';
import Transform from './Transform.js';
import TransformVR from './TransformVR.js';
import SculptVoxel from './SculptVoxel.js';
import Grab from './Grab.js';
import DeleteFace from './DeleteFace.js';
import FillHole from './FillHole.js';
import DissolveEdge from './DissolveEdge.js';
import SplitFace from './SplitFace.js';
import SpinEdge from './SpinEdge.js';
import CollapseEdge from './CollapseEdge.js';
import DissolveVertex from './DissolveVertex.js';
import Weld from './Weld.js';
import SnapWeldCenter from './SnapWeldCenter.js';
import SplitEdge from './SplitEdge.js';
import SimpleSplitEdge from './SimpleSplitEdge.js';
import EdgeCreate from './EdgeCreate.js';
import CutTool from './CutTool.js';

var Tools = [];

Tools[Enums.Tools.BRUSH] = Brush;
Tools[Enums.Tools.INFLATE] = Inflate;
Tools[Enums.Tools.TWIST] = Twist;
Tools[Enums.Tools.SMOOTH] = Smooth;
Tools[Enums.Tools.FLATTEN] = Flatten;
Tools[Enums.Tools.PINCH] = Pinch;
Tools[Enums.Tools.CREASE] = Crease;
Tools[Enums.Tools.DRAG] = Drag;
Tools[Enums.Tools.RELAX] = Relax;
Tools[Enums.Tools.PAINT] = Paint;
Tools[Enums.Tools.MOVE] = Move;
Tools[Enums.Tools.MASKING] = Masking;
Tools[Enums.Tools.LOCALSCALE] = LocalScale;
Tools[Enums.Tools.TRANSFORM] = Transform;
Tools[Enums.Tools.VOXEL] = SculptVoxel;
Tools[Enums.Tools.GRAB] = Grab;
Tools[Enums.Tools.TRANSFORM_VR] = TransformVR;
Tools[Enums.Tools.DELETE_FACE] = DeleteFace;
Tools[Enums.Tools.FILL_HOLE] = FillHole;
Tools[Enums.Tools.DISSOLVE_EDGE] = DissolveEdge;
Tools[Enums.Tools.SPLIT_FACE] = SplitFace;
Tools[Enums.Tools.SPIN_EDGE] = SpinEdge;
Tools[Enums.Tools.COLLAPSE_EDGE] = CollapseEdge;
Tools[Enums.Tools.DISSOLVE_VERTEX] = DissolveVertex;
Tools[Enums.Tools.WELD] = Weld;
Tools[Enums.Tools.SNAP_WELD_CENTER] = SnapWeldCenter;
Tools[Enums.Tools.SPLIT_EDGE] = SimpleSplitEdge;
Tools[Enums.Tools.EDGE_CREATE] = EdgeCreate;
Tools[Enums.Tools.CUT_TOOL] = CutTool;
Tools[Enums.Tools.SLIDE] = Slide;

Tools[Enums.Tools.BRUSH].uiName = 'sculptBrush';
Tools[Enums.Tools.INFLATE].uiName = 'sculptInflate';
Tools[Enums.Tools.TWIST].uiName = 'sculptTwist';
Tools[Enums.Tools.SMOOTH].uiName = 'sculptSmooth';
Tools[Enums.Tools.FLATTEN].uiName = 'sculptFlatten';
Tools[Enums.Tools.PINCH].uiName = 'sculptPinch';
Tools[Enums.Tools.CREASE].uiName = 'sculptCrease';
Tools[Enums.Tools.DRAG].uiName = 'sculptDrag';
Tools[Enums.Tools.RELAX].uiName = 'sculptRelax';
Tools[Enums.Tools.PAINT].uiName = 'sculptPaint';
Tools[Enums.Tools.MOVE].uiName = 'sculptMove';
Tools[Enums.Tools.MASKING].uiName = 'sculptMasking';
Tools[Enums.Tools.LOCALSCALE].uiName = 'sculptLocalScale';
Tools[Enums.Tools.TRANSFORM].uiName = 'sculptTransform';
Tools[Enums.Tools.VOXEL].uiName = 'sculptVoxel';
Tools[Enums.Tools.GRAB].uiName = 'sculptGrab';
Tools[Enums.Tools.TRANSFORM_VR].uiName = 'sculptTransformVR';
Tools[Enums.Tools.DELETE_FACE].uiName = 'sculptDeleteFace';
Tools[Enums.Tools.FILL_HOLE].uiName = 'sculptFillHole';
Tools[Enums.Tools.DISSOLVE_EDGE].uiName = 'sculptDissolveEdge';
Tools[Enums.Tools.SPLIT_FACE].uiName = 'sculptSplitFace';
Tools[Enums.Tools.SPIN_EDGE].uiName = 'sculptSpinEdge';
Tools[Enums.Tools.COLLAPSE_EDGE].uiName = 'sculptCollapseEdge';
Tools[Enums.Tools.DISSOLVE_VERTEX].uiName = 'sculptDissolveVertex';
Tools[Enums.Tools.WELD].uiName = 'sculptWeld';
Tools[Enums.Tools.SNAP_WELD_CENTER].uiName = 'sculptSnapWeldCenter';
Tools[Enums.Tools.SPLIT_EDGE].uiName = 'sculptSplitEdge';
Tools[Enums.Tools.EDGE_CREATE].uiName = 'sculptEdgeCreate';
Tools[Enums.Tools.CUT_TOOL].uiName = 'sculptCutTool';
Tools[Enums.Tools.SLIDE].uiName = 'sculptSlide';

export default Tools;
